/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.superloop.interview.todo;

import org.junit.Test;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        TodoListApplication classUnderTest = new TodoListApplication();
        
    }
}
